print('Please enter the following information:\n')
first=input('First name: ').capitalize()
last=input('Last name: ').upper()
email=input('Email address: ').lower()
phone=input('Phone number: ')
job=input('Job title: ').title()
id=input('ID Number: ')
hair=input('Hair color: ').capitalize()
eyes=input('Eye color: ').capitalize()
month=input('Birth month: ').capitalize()
training=input('Do you have training: ').capitalize()
print('The ID Card is:\n'+('-'*40)+f'\n{last}, {first}\n{job}\nID: {id}\n\n{email}\n{phone}\n\nHair: {hair:20}Eyes: {eyes}\nMonth: {month:19}Training: {training}\n'+('-'*40))