age = int(input('How old are you? '))
print(f'On your next birthday you will be {age+1}\n')
eggs = int(input('How many egg cartons do you have? '))
print(f'You have {eggs*12} eggs\n')
cookies = float(input('How many cookies do you have? '))
people = float(input('How many people are there? '))
print(f'Each person may have {cookies/people} cookies')